#!/usr/bin/env bash

set -eou pipefail

dir=$(dirname "$0")
source "$dir"/random_functions

port=$(get_random_port_not_used)
postgres_port=$(get_random_port_not_used)
random_secret=$(get_random_secret)
nats_server_port=$(get_random_port_not_used)

#app
export JWT_SECRET=$random_secret
export NODE_ENV=test
export PORT=$port

#docker
export COMPOSE_PROJECT_NAME=payments-api-test

#nats
export NACK_DELAY_MS=1000
export NACK_MAX_RETRIES=3
export NATS_SERVER_HOST=localhost
export NATS_SERVER_PORT=$nats_server_port


#postgres
export POSTGRES_DB=payment
export POSTGRES_HOST=localhost
export POSTGRES_PASSWORD=123456
export POSTGRES_PORT=$postgres_port
export POSTGRES_USER=jorge

#stripe -> TODO it must be a secret in Kubernetes
export STRIPE_SECRET_KEY=sk_test_51Kj8jTFCS8gMf7cqkR3poRy1wCwvY2UihXnp2nbzBdQ6G6XByIGFuoxfCtAGcGBlL2KSRfrtFGE2Vd1hL6XMuDpd00sHGss2ff
export STRIPE_API_KEY=pk_test_51Kj8jTFCS8gMf7cqOZWAsGqUwFmBKApyhClhQIVuBgNsuLEsrjZ9DFvNcZPU18N5zfMGD7WxmvfrnGIwK2kXfryV00Ks6TAI5P
