name: comment_on_pr

on:
  workflow_run:
    types:
      - completed
    workflows:
      - pull_request
jobs:
  delete-comment:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      -
        name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment-author: 'github-actions[bot]'
          body-includes: Links for artifacts
      -
        name: Delete Comment
        if: steps.find-comment.outputs.comment-id != ''
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/comments/${{ steps.find-comment.outputs.comment-id }}
  comment:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      -
        name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pull_request.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: test-report
      -
        name: Show report
        run: |
          ls -la 
          ls -la test-report
          cat test-report/test-results.json | jq
      -
        name: Analize report
        run: |
          # Extract the status field and count the number of times each value occurs
          status_counts=$(jq '.suites[].suites[].specs[].tests[].status' test-results.json | sort | uniq -c)
          
          # Extract the count of the "expected" status value
          count_expected=$(echo "$status_counts" | awk '$2 == "\"expected\"" {print $1}')
          
          # Extract the count of the "unexpected" status value
          count_unexpected=$(echo "$status_counts" | awk '$2 == "\"unexpected\"" {print $1}')
          
          # if count_unexpected is not empty, exit with 1
          if [[ -n "$count_unexpected" ]]; then
            echo "Unexpected statuses found"
          else
            echo "No unexpected statuses found"
          fi
        
          # Print the counts
          echo "Number of expected statuses: $count_expected"
          echo "Number of unexpected statuses: $count_unexpected"
      -
        name: Prepare Links
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ARTIFACT_NAME: test-report
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
        run: |
          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"
          
          check_suite_id=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/runs/${PREVIOUS_JOB_ID} \
            | jq -r '.check_suite_id')
          
          echo "check_suite_id: ${check_suite_id}"
          
          echo "ARTIFACT_NAME: ${ARTIFACT_NAME}"
          artifact_id=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/artifacts \
            | jq -r ".artifacts[] | select(.name == \"${ARTIFACT_NAME}\" and .expired == false) | select(.workflow_run.id == ${PREVIOUS_JOB_ID}) | .id")

          echo "artifact_id: ${artifact_id}"
          
          
          if [[ -n "${check_suite_id}" && -n "${artifact_id}" ]]; then
            ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/suites/${check_suite_id}/artifacts/${artifact_id}"
            echo "ARTIFACT_URL: ${ARTIFACT_URL}"
            echo "ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_ENV"
          else
            echo "ARTIFACT_URL=not-available" >> "$GITHUB_ENV"
          fi
          
          PR_NUMBER=$(jq -r '.pull_requests[0].number' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")
          
          echo "Pull request Number: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"
          
          HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")
          
          echo "Head SHA: $HEAD_SHA"
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"
      -
        name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
          body-includes: Links for artifacts
      -
        name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ env.PREVIOUS_JOB_ID }}"
          ARTIFACT_URL: ${{ env.ARTIFACT_URL }}
          HEAD_SHA: "${{ env.HEAD_SHA }}"
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ env.PR_NUMBER }}
          edit-mode: replace
          body: |-
            ![badge]
            
            Links for artifacts
            
            | Name     | Link                    |
            | -------- | ----------------------- |
            | Commit   | ${{ env.HEAD_SHA }}     |
            | Logs     | ${{ env.JOB_PATH }}     |
            | Download | ${{ env.ARTIFACT_URL }} |
            
            [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjZmZmZmZmIj48cGF0aCBkPSJNMjEuMDMgNS43MmEuNzUuNzUgMCAwIDEgMCAxLjA2bC0xMS41IDExLjVhLjc0Ny43NDcgMCAwIDEtMS4wNzItLjAxMmwtNS41LTUuNzVhLjc1Ljc1IDAgMSAxIDEuMDg0LTEuMDM2bDQuOTcgNS4xOTVMMTkuOTcgNS43MmEuNzUuNzUgMCAwIDEgMS4wNiAwWiI+PC9wYXRoPjwvc3ZnPg==
          reactions: eyes
