name: pull_request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  code_quality_check:
    uses: ./.github/workflows/code-quality-check.yml
    secrets: inherit
  test-report: #maybe in the same code_quality_check job
    runs-on: ubuntu-latest
    needs: [code_quality_check]
    if: ${{ failure() && needs.code_quality_check.outputs.tests-failed == 'true' }}
    steps:
      -
        name: Some test failed
        run: echo "Some test failed"
#      - name: Download artifact and send to comment in the pr
#        uses: ./.github/actions/test-report
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          pr-number: ${{ github.event.number }}
#          repo-name: ${{ github.repository }}
#          repo-owner: ${{ github.repository_owner }}
  comment-on-pr:
    runs-on: ubuntu-latest
    needs: [ code_quality_check ]
    if: ${{ failure() && needs.code_quality_check.outputs.tests-failed == 'true' }}
    steps:
      - name: Get Artifact and Pull request info
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          # Current job id
          CURRENT_JOB_ID=$(echo $GITHUB_JOB | cut -d'.' -f1)
          # Set in github env the CURRENT_JOB_ID
          echo "CURRENT_JOB_ID=$CURRENT_JOB_ID" >> $GITHUB_ENV

#      - name: Find Comment
#        uses: peter-evans/find-comment@v2
#        id: find-comment
#        with:
#          issue-number: ${{ github.event.number }}
#          comment-author: 'github-actions[bot]'
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number:  ${{ github.event.pull_request.number }}
#          comment-id: ${{ steps.find-comment.outputs.comment-id }}
#          edit-mode: replace
          body:  |
            **Edit:** Some additional info
          reactions: eyes
