name: Run tests

on:
  # manual trigger
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    env:
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Clean install only the dependencies
        working-directory: ./src
        run: |
          npm ci --omit=dev
      - run: docker compose -f scripts/docker-compose.test.yml pull
      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}-{hash}
            docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
            docker-layer-caching-${{ github.workflow }}-${{ github.event_name }}
            docker-layer-caching-${{ github.workflow }}
            docker-layer-caching-
        continue-on-error: true
      - name: Run tests
        working-directory: ./src
        run: |
          npm run test
