name: pull_request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  code_quality_check:
    uses: ./.github/workflows/code-quality-check.yml
    secrets: inherit
  test-report:
    runs-on: ubuntu-latest
    needs: [code_quality_check]
    if: ${{ failure() && needs.code_quality_check.outputs.tests-failed == 'true' }}
    steps:
      -
        name: Some test failed
        run: echo "Some test failed"
#      - name: Download artifact and send to comment in the pr
#        uses: ./.github/actions/test-report
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          pr-number: ${{ github.event.number }}
#          repo-name: ${{ github.repository }}
#          repo-owner: ${{ github.repository_owner }}
