name: Code Quality Check

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'tests/**'

env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  lint:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: env
      - name: Clean install with dev dependencies
        run: |
          npm ci
      - name: Linting
        run: |
          npm run lint
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    environment: testing
    env:
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull images
        run: docker compose -f scripts/docker-compose.test.yml pull
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Clean install
        run: |
          npm ci --omit=dev
      - name: Run tests
        run: |
          npm run test
