name: pull_request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  code_quality_check:
    uses: ./.github/workflows/code-quality-check.yml
    secrets: inherit
  test-report: #maybe in the same code_quality_check job
    runs-on: ubuntu-latest
    needs: [code_quality_check]
    if: ${{ failure() && needs.code_quality_check.outputs.tests-failed == 'true' }}
    steps:
      -
        name: Some test failed
        run: echo "Some test failed"
#      - name: Download artifact and send to comment in the pr
#        uses: ./.github/actions/test-report
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          pr-number: ${{ github.event.number }}
#          repo-name: ${{ github.repository }}
#          repo-owner: ${{ github.repository_owner }}
  comment-on-pr:
    runs-on: ubuntu-latest
    needs: [ code_quality_check ]
    if: ${{ failure() && needs.code_quality_check.outputs.tests-failed == 'true' }}
    steps:
      - name: Get Artifact and Pull request info
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          # Set PR_NUMBER to the PR number if it is a pull request
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            PR_NUMBER=$GITHUB_EVENT_NUMBER
            echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV  
          fi
          # Current job id
          CURRENT_JOB_ID=$(echo $GITHUB_JOB | cut -d'.' -f1)
          # Set in github env the CURRENT_JOB_ID
          echo "CURRENT_JOB_ID=$CURRENT_JOB_ID" >> $GITHUB_ENV

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
      - name: Update Comment
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ env.CURRENT_JOB_ID }}"
          ARTIFACT_URL: "${{ github.server_url }}/${{ github.repository }}/suites/$SUITE_ID/artifacts/$ARTIFACT_ID"
          HEAD_SHA: "${{ env.HEAD_SHA }}"
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |-
            ![badge]
            
            Build Successful! You can find a link to the downloadable artifact below.
            
            | Name     | Link                    |
            | -------- | ----------------------- |
            | Commit   | ${{ env.HEAD_SHA }}     |
            | Logs     | ${{ env.JOB_PATH }}     |
            | Download | ${{ env.ARTIFACT_URL }} |
            
            [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjZmZmZmZmIj48cGF0aCBkPSJNMjEuMDMgNS43MmEuNzUuNzUgMCAwIDEgMCAxLjA2bC0xMS41IDExLjVhLjc0Ny43NDcgMCAwIDEtMS4wNzItLjAxMmwtNS41LTUuNzVhLjc1Ljc1IDAgMSAxIDEuMDg0LTEuMDM2bDQuOTcgNS4xOTVMMTkuOTcgNS43MmEuNzUuNzUgMCAwIDEgMS4wNiAwWiI+PC9wYXRoPjwvc3ZnPg==