name: pull-request

on:
  # manual trigger
  workflow_dispatch:
#  pull_request:
#    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    env:
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      COMPOSE_PROJECT_NAME: payments-api-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Clean install only the dependencies
        working-directory: ./src
        run: |
          npm ci --omit=dev
      - name: Run tests
        working-directory: ./src
        run: |
          npm run test
